version: "3.7"

services:
  php:
    build:
      args:
        user: user
        uid: 1000
      context: ./docker/php
    image: infusemedia-task
    container_name: infusemedia-task-php
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    depends_on:
      db:
        condition: service_healthy
    networks:
      - infusemedia-task

  db:
    image: mysql:8.0
    container_name: infusemedia-task-db
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: views
    volumes:
      - ./docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 40
    networks:
      - infusemedia-task

  nginx:
    image: nginx:1.22
    container_name: infusemedia-task-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d/
    depends_on:
      - php
      - db
    networks:
      - infusemedia-task

networks:
  infusemedia-task:
    driver: bridge
